### ISSUE TITLE
Cryptic error with Python 3.12

### ISSUE THREAD

**Issue by cdeil** [posit-dev/rsconnect-python#612]
I just made an account at https://shiny.posit.co/py/docs/deploy-cloud.html and fetched the template https://shiny.posit.co/py/templates/dashboard/ and tried to deploy it.

Got this error:
```
$ rsconnect deploy shiny dashboard --name cdeil --title penguin-dashboard
Validating server...    [OK]
Validating app mode...  [OK]
Making bundle ...       [OK]
Deploying bundle ...
Waiting for task: 1439006162
  building - Parsing manifest
[ERROR] 2024-07-20T10:59:43+0200 Build logs:

        [ERROR]: Application deployment failed with error: Unhandled Exception: child_task=1439006163 child_task_status=error: Unhandled Exception: Unsupported python version 3.2.3 for operating system jammy.
Error: Application deployment failed with error: Unhandled Exception: child_task=1439006163 child_task_status=error: Unhandled Exception: Unsupported python version 3.2.3 for operating system jammy.
```

Other users are running into the same error:

https://forum.posit.co/t/cannot-deploy-shiny-app-to-shinyapps-io-unsupported-python-version-3-2-3-for-operating-system-jammy/188630

I think there's some bug where your deployment mistakes Python 3.12 which I have locally with Python 3.2 ?

Can you please support Python 3.12 ?

Or fix this Python version detection and give a correct error message?

What's the workaround? I have to choose Python 3.11 locally also to make it work?

**Comment by ssinnott** [comment]
Ok should be all fixed up now,
1) Docs has been updated.
2) I cleaned up the error message - so if a major/minor version of python is missing it should give a better error message.
3) I also added python 3.12.3 - so any 3.12 version used to deploy should pick that up now.

**Comment by cdeil** [comment]
@ssinnott - thanks!

It works for me.

What is the command to deploy app updates after an application code edit?

Do I simply keep running this or is there a better way?

```
$ rsconnect deploy shiny . --name cdeil --title penguin-dashboard
```

Would be great if that could be mentioned somewhere in the docs, e.g. here:

https://shiny.posit.co/py/docs/deploy-cloud.html

**Comment by LangeTo** [comment]
That's how I do it, this overwrites the current app on shinyapps.io with your just deployed version.
