### ISSUE TITLE
Add `--force` flag for build process

### ISSUE THREAD

**Issue by fizzboop** [posit-dev/rsconnect-python#620]
# Problem

Currently, if there is an [interruption](https://github.com/posit-dev/rsconnect-python/blob/395861b66fc596cacf07fea0b81745282e39b875/rsconnect/actions_content.py#L162) during the build process, a user is stuck in a state where they are [unable](https://github.com/posit-dev/rsconnect-python/blob/395861b66fc596cacf07fea0b81745282e39b875/rsconnect/actions_content.py#L234-L258) to build. Customer have been encountering this issue and reaching out to Support.

# Possible Solution

As a workaround, we could add a `--force` to help users get pass the build error.

**Comment by lucasrod16** [comment]
Fixed in #630
